export { default as userController } from './user.controller'
export { default as authController } from './auth.controller'
export { default as templateController } from './template.controller'
export { default as assetController } from './asset.controller'
export { default as sentenceController } from './sentence.controller'
